spring:
  datasource:
    username: root
    password: root
    #url: jdbc:mysql:///test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://139.159.201.187:3306/patrol_inspect_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
## 蛇形（a_b_c）的参数 是不是转换成 aBC
#mybatis.configuration.mapUnderscoreToCamelCase: true
## mybatis 日志配置，将sql执行过程在控制台上输出
#mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/pc/*Mapper.xml
#mybatis's properties
